### ISSUE TITLE
2015 Minnesota State High School League from #moardata

### ISSUE THREAD

**Issue by Chri2693** [the-blue-alliance/the-blue-alliance-data#20]
I transferred the FMS data provided by Doug Frisk for the 2015 Minnesota State High School League Championship to the importer format: https://www.facebook.com/groups/moardata/930747813612181/

**Comment by gregmarra** [comment]
Added after a huge delay! Sorry and thanks for contributing! http://www.thebluealliance.com/event/2015mnsc
