### ISSUE TITLE
2015GLBBB Match Data & More

### ISSUE THREAD

**Issue by cbale2000** [the-blue-alliance/the-blue-alliance-data#23]
Match results, ranks, and awards data for the "Great Lakes Bay Bot Bash 2015" off-season competition (spreadsheet uploaded to the #moardata FB group).

Wasn't sure if I needed to also provide the qualifying averages (there were some surrogate matches so I assume it can't be automatically calculated) or if you guys just skip that data when it isn't provided. The team ranks at the end of Quals are provided on the last tab of the spreadsheet regardless.

Thanks!

**Comment by gregmarra** [comment]
This was added. Thanks!

We should auto-calculate rankings, etc.
