### ISSUE TITLE
Where's the match data?

### ISSUE THREAD

**Issue by Tormenator1** [the-blue-alliance/the-blue-alliance-data#45]
Hey,I see other issues mentioning match data,but I can't seem to find the csv files for match data. If I'm missing something obvious let me know. Thanks.

**Comment by gregmarra** [comment]
@Tormenator1 you can see match data inside of each event folder, for example https://github.com/the-blue-alliance/the-blue-alliance-data/tree/master/events/2018/2018arli

We have not updated the CSV data with 2019 data yet, you can see the last commit was January 11th, 2019: https://github.com/the-blue-alliance/the-blue-alliance-data/commits/master

Are you looking for 2019 match data? For now, it's available via the Read API: https://www.thebluealliance.com/apidocs

**Comment by Tormenator1** [comment]
Alright. Thank you.
