### ISSUE TITLE
[bad data] waterloo country, 1997cmp award

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance-data#47]
https://www.facebook.com/groups/moardata/permalink/2331451383541810/

Data Errors:
* Waterloo Regional 2006-2008 is listed as Waterloo USA for some reason. 2005 and 2009 are correct.
* 1997cmp has 1817 listed as a team receiving the judges award several years before their rookie year.

**Comment by fangeugene** [comment]
Fixed Waterloo. Not sure what to do about 1817.

**Comment by ZachOrr** [comment]
From Slack

> 1817 did win Judges in 1997, because they're actually 137 who FIRST gave a new number b/c they didn't keep track of well enough.
