### ISSUE TITLE
Team History pages broken for all events after Einstein 2016

### ISSUE THREAD

**Issue by ryguy12345** [the-blue-alliance/the-blue-alliance-data#89]
It appears that Team History pages are missing the respective award listings for all events following Einstein 2016. See example for 118 below; their Dean's List Finalist on Einstein 2016 is listed, but their wins at IRI 2016 and Texas Robot Roundup 2016 (and all events afterwards) are not. 

https://www.thebluealliance.com/team/118/history

**Comment by dracco1993** [comment]
Thanks for reporting this!

For bookkeeping, here is the corresponding code issue link:
the-blue-alliance/the-blue-alliance#3276

**Comment by phil-lopreiato** [comment]
Fixed with upstream issue
