### ISSUE TITLE
Duplicate WFFAs at events

### ISSUE THREAD

**Issue by tervay** [the-blue-alliance/the-blue-alliance-data#90]
Duplicate WFFAs as a result of misspelling at:

* 2019paca
* 2018arli
* 2016casd
* 2014tnkn

**Comment by ZachOrr** [comment]
`2019paca`, `2016casd`, and `2014tnkn` actually had the same spellings for both recipients, from what I could tell.

Fixed these for the events above. It might be worth us writing a script to run quick on the prod DB to identify anywhere else this has happened (look for award type 3 with multiple recipients)
