### ISSUE TITLE
Wrong match numbers for 2007sac qf1

### ISSUE THREAD

**Issue by tervay** [the-blue-alliance/the-blue-alliance-data#92]
https://www.thebluealliance.com/event/2007sac

![J5umi93](https://user-images.githubusercontent.com/7595639/122334498-d62e2080-cf07-11eb-98e4-9c7a70972668.png)

These should be qf1-1, qf1-2, qf1-3, not qf1-3, qf1-4, qf1-5

**Comment by ZachOrr** [comment]
Fixed 
<img width="596" alt="Screen Shot 2021-06-17 at 12 06 04 PM" src="https://user-images.githubusercontent.com/516458/122433633-68fca880-cf64-11eb-8525-83d86deffb95.png">
